name: '#PRKrigAU2016'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32888
title: '#PRKrigAU2016'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74933848-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3007b'
    - '#e3007c'
    - '#e4007b'
    - '#e4007c'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
