name: PRKrigAU2016
favicon: null
layout_spectrum: 0.6809243154712021
typography_spectrum: 0.6579909110441804
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6320339646190405
  lightness: 0.0674321309197694
  saturation: 0.29883175645954907
  rhythmicContrast: 0.5051335531752557
purpose: []
