name: '#PRKrigAU2016'
favicon: null
layout_spectrum: 0.92154
typography_spectrum: 0.32888
title: '#PRKrigAU2016'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74933848-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#000000'
    - '#d14343'
    - '#1e5268'
    - '#cf72f6'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
