name: '#PRKrigAU2016'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32888
title: '#PRKrigAU2016'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74933848-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff084a'
    - '#ffc2cd'
    - '#fc3468'
    - '#ff6289'
    - '#ff93ac'
  brandStrength: 0.0625
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
