name: '#PRKrigAU2016'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32888
title: '#PRKrigAU2016'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74933848-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#eb6b8f'
    - '#ddaafa'
    - '#707070'
    - '#b5d755'
  brandStrength: 0.0625
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
